### ISSUE TITLE
Newnet is broken

### ISSUE THREAD

**Issue by pnielsen2** [HaxballAI/haxball#3]
AttributeError: Can't get attribute 'convertFrame' on <module '__main__' from 'C:\\Users\\Philip Nielsen\\Documents\\haxball\\model_starter.py'>

**Comment by aDifferentJT** [comment]
Please could you give steps required to reproduce the error

**Comment by aDifferentJT** [comment]
Scrub that, I know what’s wrong and will fix now

**Comment by aDifferentJT** [comment]
Fixed
